name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH(원격 접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }} # 원격 서버의 주석
          username: ${{ secrets.EC2_USERNAME }} # 인스턴스를 시작하는 데 사용되는 AMI에 정의된 사용자 이름
          key: ${{ secrets.EC2_KEY }} # 키페어 값
          script_stop: true
          script: |
            cd /home/ubuntu/cicd-practice
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &